config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/horizontal-adapters:
      branch: main
      repo: https://github.com/madgeek-arc/horizontal-adapters
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/horizontal-adapters git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-ivory-pig.sh
        container: qc.acc_squirrely-chestnut-wallaby
  QC.Doc:
    repos:
      github.com/madgeek-arc/horizontal-adapters find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-orchid-dogfish.sh
        container: qc.doc_cheeky-gold-squirrel
      github.com/madgeek-arc/horizontal-adapters git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-olivine-millipede.sh
        container: qc.doc_bumpy-ivory-wildebeest
      github.com/madgeek-arc/horizontal-adapters markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-olive-kingfisher.sh
        container: qc.doc_randy-purple-lizard
  QC.Lic:
    repos:
      github.com/madgeek-arc/horizontal-adapters licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cardinal-malamute.sh
        container: qc.lic_thirsty-cerulean-angora
  QC.Sec:
    repos:
      github.com/madgeek-arc/horizontal-adapters bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-lavender-falcon.sh
        container: qc.sec_slimy-olivine-drever
  QC.Sty:
    repos:
      github.com/madgeek-arc/horizontal-adapters checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-peach-bordeaux.sh
        container: qc.sty_wiggy-emerald-chameleon
      github.com/madgeek-arc/horizontal-adapters flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-lemon-coral.sh
        container: qc.sty_ready-brown-macaw
  QC.Uni:
    repos:
      github.com/madgeek-arc/horizontal-adapters pytest:
        commands:
        - /usr/bin/env sh .sqa/script.messy-green-whale.sh
        container: qc.uni_boozy-azure-caracal
  QC.Ver:
    repos:
      github.com/madgeek-arc/horizontal-adapters get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-chartreuse-anteater.sh
        container: qc.ver_slimy-persimmon-crab
timeout: 5400
