config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/horizontal-adapters:
      branch: main
      repo: https://github.com/madgeek-arc/horizontal-adapters
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/horizontal-adapters git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-wisteria-barb.sh
        container: qc.acc_sloppy-linen-chinchilla
  QC.Doc:
    repos:
      github.com/madgeek-arc/horizontal-adapters find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-dandelion-bonobo.sh
        container: qc.doc_cozy-carmine-hyrax
      github.com/madgeek-arc/horizontal-adapters git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-chestnut-sheepdog.sh
        container: qc.doc_greasy-sapphire-harrier
      github.com/madgeek-arc/horizontal-adapters markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-wheat-greyhound.sh
        container: qc.doc_droopy-maroon-bandicoot
  QC.Lic:
    repos:
      github.com/madgeek-arc/horizontal-adapters licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-platinum-wasp.sh
        container: qc.lic_hilly-chocolate-flamingo
  QC.Sec:
    repos:
      github.com/madgeek-arc/horizontal-adapters bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cyan-skunk.sh
        container: qc.sec_scanty-corn-penguin
  QC.Sty:
    repos:
      github.com/madgeek-arc/horizontal-adapters checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-indigo-goat.sh
        container: qc.sty_cranky-aqua-dragonfly
      github.com/madgeek-arc/horizontal-adapters flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-beige-quokka.sh
        container: qc.sty_tacky-myrtle-fish
  QC.Uni:
    repos:
      github.com/madgeek-arc/horizontal-adapters pytest:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cerulean-boar.sh
        container: qc.uni_fuzzy-ultramarine-gharial
  QC.Ver:
    repos:
      github.com/madgeek-arc/horizontal-adapters get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-razzmatazz-foxhound.sh
        container: qc.ver_shaggy-emerald-tarsier
timeout: 5400
